In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('../output/fatal-police-shootings-data.csv')
len(data)

10430

In [4]:
data.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,A,not_available,True,False,73
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,W,not_available,False,False,70
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,H,not_available,False,False,238
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,W,not_available,True,False,196
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,H,not_available,False,False,473

In [4]:
data.tail()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
10425,11283,2024-12-30,undetermined,NaN,knife,Sacramento,Sacramento,CA,38.494163,-121.355656,block,NaN,38.0,male,NaN,NaN,True,True,1069
10426,11284,2024-12-30,threat,foot,gun,Orlando,Orange,FL,28.580447,-81.445027,block,Timothy Woods,26.0,male,B,photo,False,False,482
10427,11286,2024-12-30,undetermined,NaN,unknown,West Point,Davis,UT,41.122823,-112.070576,address,Nathan Paul,43.0,male,NaN,NaN,True,False,1450
10428,11285,2024-12-31,threat,not,gun,Chattanooga,Hamilton,TN,35.044135,-85.149670,address,James Junior Holder,41.0,male,W,photo,False,False,750
10429,11287,2024-12-31,attack,NaN,knife,Celina,Mercer,OH,40.546807,-84.570866,address,Moses Alik,22.0,male,NaN,NaN,False,False,17378

In [5]:
data.state

0        WA
1        OR
2        KS
3        CA
4        CO
         ..
10425    CA
10426    FL
10427    UT
10428    TN
10429    OH
Name: state, Length: 10430, dtype: str

In [6]:
data.dtypes

id                              int64
date                              str
threat_type                       str
flee_status                       str
armed_with                        str
city                              str
county                            str
state                             str
latitude                      float64
longitude                     float64
location_precision                str
name                              str
age                           float64
gender                            str
race                              str
race_source                       str
was_mental_illness_related       bool
body_camera                      bool
agency_ids                        str
dtype: object

In [9]:
# What is the time range of the available data? Use a line of pandas code to find out. 
data["date"].min(), data["date"].max()

('2015-01-02', '2024-12-31')

In [11]:
# Say you want to analyze the racial disparities in this dataset, broken down by race and by the larger category of non-white people. 
# Write a line of code that takes a look at the universe of values in the race column.

data['race'].value_counts()

race
W        4659
B        2486
H        1717
A         184
N         146
O          37
W;B         4
W;H         3
B;H         3
W;B;N       1
N;H         1
W;A         1
Name: count, dtype: int64

In [13]:
# Make the letters in the race column all lower-case

data['race'] = data['race'].str.lower()

In [15]:
data.tail()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
10425,11283,2024-12-30,undetermined,NaN,knife,Sacramento,Sacramento,CA,38.494163,-121.355656,block,NaN,38.0,male,NaN,NaN,True,True,1069
10426,11284,2024-12-30,threat,foot,gun,Orlando,Orange,FL,28.580447,-81.445027,block,Timothy Woods,26.0,male,b,photo,False,False,482
10427,11286,2024-12-30,undetermined,NaN,unknown,West Point,Davis,UT,41.122823,-112.070576,address,Nathan Paul,43.0,male,NaN,NaN,True,False,1450
10428,11285,2024-12-31,threat,not,gun,Chattanooga,Hamilton,TN,35.044135,-85.149670,address,James Junior Holder,41.0,male,w,photo,False,False,750
10429,11287,2024-12-31,attack,NaN,knife,Celina,Mercer,OH,40.546807,-84.570866,address,Moses Alik,22.0,male,NaN,NaN,False,False,17378

In [17]:
# Create a new column called "poc" and use a lambda function to set it equal to True or False based on the information in the race column.
data['poc'] = data['race'].apply(lambda x: False if x == 'white' else True)
# How many rows are POC and how many are White?
data['poc'] = data['race'].apply(lambda x: False if x == 'white' else (True if pd.notnull(x) else None))

In [19]:
data['poc'].value_counts()

poc
True    9242
Name: count, dtype: int64

In [18]:
data.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids,poc
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,a,not_available,True,False,73,True
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,w,not_available,False,False,70,True
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,h,not_available,False,False,238,True
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,w,not_available,True,False,196,True
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,h,not_available,False,False,473,True

In [26]:
# I want to know which county had the most police killings but some counties in the U.S. have the same name. 
# Create a column called country_state and populate it with the county and the state to create unique pairs. 
data["county_state"] = data["county"] + ", " + data["state"]

In [27]:
# Now answer the question: which county had the most killings?
data["county_state"].value_counts().idxmax()

'Los Angeles, CA'

In [28]:
# Create a new column called "unarmed" and use a lambda function to set it to True/False based on the relevant info.
data["unarmed"] = data["armed_with"].apply(lambda x: True if str(x).lower() == "unarmed" else False)

# Create a subset of the data for unarmed killings and store it in a new variable called unarmed_killings. 
unarmed_killings = data[data["unarmed"] == True]

# Which county had the most of these?
unarmed_killings["county_state"].value_counts().idxmax()

'Los Angeles, CA'

In [29]:
# We could have done that more smoothly using a groupby. So let's do that. 
# Group the original dataset by your new columns unarmed killings and county_state. 
grouped = data.groupby(["unarmed", "county_state"]).size().to_frame(name="killings_count")
 
# Use loc[] to isolate the rows where unarmed==True
unarmed_grouped = grouped.loc[True]

# Sort from highest #killings to lowest
unarmed_grouped.sort_values(by="killings_count", ascending=False)

                 killings_count
county_state
Los Angeles, CA              19
Orange, CA                    7
Harris, TX                    6
San Diego, CA                 6
Maricopa, AZ                  6
...                         ...
Williamson, TX                1
Winnebago, WI                 1
Wood, TX                      1
Yalobusha, MS                 1
Yamhill, OR                   1

[219 rows x 1 columns]

 I want to examine the data by race and gender to understand whether Black women are disproportionately killed by the police compared to white women and by how much. I'm not going to tell you what to do beyond that — this is where you need to think creatively as a data reporter! What information do you need to look up to figure out this answer? Go step by step and show your working using Python comments.

In [36]:
#I'm filtering the dataset for just women and then creating a column for black women and white women

female_data = data[data["gender"] == "female"].copy()

women_by_race = female_data.groupby("race").size().to_frame(name="killings_count")

women_by_race = women_by_race.sort_values(by="killings_count", ascending=False)

In [35]:
print(women_by_race)

      killings_count
race
a                 11
b                 88
h                 59
n                  8
n;h                1
o                  4
w                254

Your editor wants you to examine mental illness in police killings in the US by state. Seeing which state had the most killings of mentally ill people is not enough; you'll need to scale by population. To do that, you will use the Python census library to access Census data. You'll need an API key to use it.

Sign up for a Census API key at this website: https://api.census.gov/data/key_signup.html

Then check your email to get the API key. Make sure to click the activation link in the email.

In [37]:
# install the python census library.
%pip install census
%pip install geonamescache

Collecting census
  Downloading census-0.8.27-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: requests>=1.1.0 in /Users/fariharahman/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from census) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/fariharahman/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from requests>=1.1.0->census) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/fariharahman/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from requests>=1.1.0->census) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/fariharahman/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from requests>=1.1.0->census) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/fariharahman/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from requests>=1.1.0->census) (2026.1.4)
Downloading census-0.8.27-py3-none-any.whl (11 kB)
Installing collected packages: census
Successfully installed census-0.8.27
Note: you may need to restart the kernel to use updated packages.
Collecting geonamescache
  Downloading geonamescache-3.0.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: typing-extensions in /Users/fariharahman/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from geonamescache) (4.15.0)
Downloading geonamescache-3.0.2-py3-none-any.whl (35.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 33.2 MB/s  0:00:01m0:00:0100:01
Installing collected packages: geonamescache
Successfully installed geonamescache-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [41]:
api_key = "9c684ef6dec7c688fb2f6f8626996898ccf68b14"

In [38]:
import os
from census import Census
from us import states
import geonamescache

In [39]:
gc = geonamescache.GeonamesCache()
us_states = gc.get_us_states()

# The geonamescache library stores the fips code for each state. 
# Adjust the loop I have below to populate the empty dictionary below, 
# where the keys are state codes (i.e. AK) and the values are fips codes (as strings)

state_to_fips = {}

for state_code, state_info in us_states.items():
    state_to_fips[state_info['code']] = state_info['fips']

for state_code, state_info in us_states.items():
    print(state_info)

{'code': 'AK', 'name': 'Alaska', 'fips': '02', 'geonameid': 5879092}
{'code': 'AL', 'name': 'Alabama', 'fips': '01', 'geonameid': 4829764}
{'code': 'AR', 'name': 'Arkansas', 'fips': '05', 'geonameid': 4099753}
{'code': 'AZ', 'name': 'Arizona', 'fips': '04', 'geonameid': 5551752}
{'code': 'CA', 'name': 'California', 'fips': '06', 'geonameid': 5332921}
{'code': 'CO', 'name': 'Colorado', 'fips': '08', 'geonameid': 5417618}
{'code': 'CT', 'name': 'Connecticut', 'fips': '09', 'geonameid': 4831725}
{'code': 'DC', 'name': 'District of Columbia', 'fips': '11', 'geonameid': 4138106}
{'code': 'DE', 'name': 'Delaware', 'fips': '10', 'geonameid': 4142224}
{'code': 'FL', 'name': 'Florida', 'fips': '12', 'geonameid': 4155751}
{'code': 'GA', 'name': 'Georgia', 'fips': '13', 'geonameid': 4197000}
{'code': 'HI', 'name': 'Hawaii', 'fips': '15', 'geonameid': 5855797}
{'code': 'IA', 'name': 'Iowa', 'fips': '19', 'geonameid': 4862182}
{'code': 'ID', 'name': 'Idaho', 'fips': '16', 'geonameid': 5596512}
{'code': 'IL', 'name': 'Illinois', 'fips': '17', 'geonameid': 4896861}
{'code': 'IN', 'name': 'Indiana', 'fips': '18', 'geonameid': 4921868}
{'code': 'KS', 'name': 'Kansas', 'fips': '20', 'geonameid': 4273857}
{'code': 'KY', 'name': 'Kentucky', 'fips': '21', 'geonameid': 6254925}
{'code': 'LA', 'name': 'Louisiana', 'fips': '22', 'geonameid': 4331987}
{'code': 'MA', 'name': 'Massachusetts', 'fips': '25', 'geonameid': 6254926}
{'code': 'MD', 'name': 'Maryland', 'fips': '24', 'geonameid': 4361885}
{'code': 'ME', 'name': 'Maine', 'fips': '23', 'geonameid': 4971068}
{'code': 'MI', 'name': 'Michigan', 'fips': '26', 'geonameid': 5001836}
{'code': 'MN', 'name': 'Minnesota', 'fips': '27', 'geonameid': 5037779}
{'code': 'MO', 'name': 'Missouri', 'fips': '29', 'geonameid': 4398678}
{'code': 'MS', 'name': 'Mississippi', 'fips': '28', 'geonameid': 4436296}
{'code': 'MT', 'name': 'Montana', 'fips': '30', 'geonameid': 5667009}
{'code': 'NC', 'name': 'North Carolina', 'fips': '37', 'geonameid': 4482348}
{'code': 'ND', 'name': 'North Dakota', 'fips': '38', 'geonameid': 5690763}
{'code': 'NE', 'name': 'Nebraska', 'fips': '31', 'geonameid': 5073708}
{'code': 'NH', 'name': 'New Hampshire', 'fips': '33', 'geonameid': 5090174}
{'code': 'NJ', 'name': 'New Jersey', 'fips': '34', 'geonameid': 5101760}
{'code': 'NM', 'name': 'New Mexico', 'fips': '35', 'geonameid': 5481136}
{'code': 'NV', 'name': 'Nevada', 'fips': '32', 'geonameid': 5509151}
{'code': 'NY', 'name': 'New York', 'fips': '36', 'geonameid': 5128638}
{'code': 'OH', 'name': 'Ohio', 'fips': '39', 'geonameid': 5165418}
{'code': 'OK', 'name': 'Oklahoma', 'fips': '40', 'geonameid': 4544379}
{'code': 'OR', 'name': 'Oregon', 'fips': '41', 'geonameid': 5744337}
{'code': 'PA', 'name': 'Pennsylvania', 'fips': '42', 'geonameid': 6254927}
{'code': 'RI', 'name': 'Rhode Island', 'fips': '44', 'geonameid': 5224323}
{'code': 'SC', 'name': 'South Carolina', 'fips': '45', 'geonameid': 4597040}
{'code': 'SD', 'name': 'South Dakota', 'fips': '46', 'geonameid': 5769223}
{'code': 'TN', 'name': 'Tennessee', 'fips': '47', 'geonameid': 4662168}
{'code': 'TX', 'name': 'Texas', 'fips': '48', 'geonameid': 4736286}
{'code': 'UT', 'name': 'Utah', 'fips': '49', 'geonameid': 5549030}
{'code': 'VA', 'name': 'Virginia', 'fips': '51', 'geonameid': 6254928}
{'code': 'VT', 'name': 'Vermont', 'fips': '50', 'geonameid': 5242283}
{'code': 'WA', 'name': 'Washington', 'fips': '53', 'geonameid': 5815135}
{'code': 'WI', 'name': 'Wisconsin', 'fips': '55', 'geonameid': 5279468}
{'code': 'WV', 'name': 'West Virginia', 'fips': '54', 'geonameid': 4826850}
{'code': 'WY', 'name': 'Wyoming', 'fips': '56', 'geonameid': 5843591}

In [42]:
# Ping the Census API with your key...
c = Census("9c684ef6dec7c688fb2f6f8626996898ccf68b14", year=2023)

# We're using American Community Survey Version 5 (acs5 in the census library)
# Population is represented by data code "B01003_001E"
# So to pull the population for New York state, which is FIPS code 36, here's what you do:

ny_population_query = c.acs5.state(("NAME", "B01003_001E"), "36" )
print(ny_population_query)

# Examine the results of the query. Looks like the Census API hands back a list with a dictionary in it, 
# and you have to pull the population info out of that...

[{'NAME': 'New York', 'B01003_001E': 19872319.0, 'state': '36'}]

In [49]:
print(f"The population of New York is: {ny_population_query[0]['B01003_001E']}")

The population of New York is: 19872319.0

In [55]:
# OK now use the state_to_fips dictionary you made in conjunction with the census API to create one more dictionary
# where keys are the state code and values are the population, ie. {"AK":3423908,"AL": .... }

# This might take a while to run! You're pinging an API 50 times. 

state_population = {}    

# Your loop here!
for state_code, fips_code in state_to_fips.items():
    try:
        query_result = c.acs5.state('B01003_001E', fips_code)
        population = int(query_result[0]['B01003_001E'])
        state_population[state_code] = population
        
    except Exception as e:
        print(f"Skipping {state_code} due to an error: {e}")

In [57]:
print(state_population)

{'AK': 733971, 'AL': 5054253, 'AR': 3032651, 'AZ': 7268175, 'CA': 39242785, 'CO': 5810774, 'CT': 3598348, 'DC': 672079, 'DE': 1005872, 'FL': 21928881, 'GA': 10822590, 'HI': 1445635, 'IA': 3195937, 'ID': 1893296, 'IL': 12692653, 'IN': 6811752, 'KS': 2937569, 'KY': 4510725, 'LA': 4621025, 'MA': 6992395, 'MD': 6170738, 'ME': 1377400, 'MI': 10051595, 'MN': 5713716, 'MO': 6168181, 'MS': 2951438, 'MT': 1105072, 'NC': 10584340, 'ND': 779361, 'NE': 1965926, 'NH': 1387834, 'NJ': 9267014, 'NM': 2114768, 'NV': 3141000, 'NY': 19872319, 'OH': 11780046, 'OK': 3995260, 'OR': 4238714, 'PA': 12986518, 'RI': 1095371, 'SC': 5212774, 'SD': 899194, 'TN': 6986082, 'TX': 29640343, 'UT': 3331187, 'VA': 8657499, 'VT': 645254, 'WA': 7740984, 'WI': 5892023, 'WV': 1784462, 'WY': 579761}

{}
I want you to learn to use the Census API because, chances are, it will be useful data to merge/explore as you work on your projects.

OK. Now back to our data on police shootings. Use pandas and the census library to figure out which state has the highest rate of police killings of disabled people. There isn't one way to get the answer! Think creatively.

In [58]:
mental_health_by_state = data.groupby("state")["was_mental_illness_related"].sum().to_frame(name="mental_health_killings")

mental_health_by_state = mental_health_by_state.sort_values(by="mental_health_killings", ascending=False)

print(mental_health_by_state)

       mental_health_killings
state
CA                        274
TX                        168
FL                        166
OH                         72
WA                         70
AZ                         70
NC                         64
GA                         63
NY                         63
TN                         61
PA                         52
OK                         51
IN                         49
MI                         49
CO                         47
OR                         44
VA                         43
MO                         42
AL                         42
WI                         38
NV                         37
LA                         36
IL                         35
NM                         35
MD                         34
SC                         30
MN                         29
UT                         29
NJ                         22
AR                         20
KY                         20
KS                         20
MA                         19
MS                         17
WV                         16
NH                         14
SD                         12
ID                         12
IA                         12
NE                         11
AK                         10
MT                          9
HI                          8
ME                          8
ND                          6
CT                          6
VT                          6
WY                          6
DC                          5
DE                          4
RI                          1